services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # 👈 this line
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:     # 👈 named volume created by Docker
